version: '2'
services:
  php:
    build: docker/php
    container_name: gothinkster_php
    volumes:
      - ./:/var/www/gothinkster
    working_dir: /var/www/gothinkster
    expose:
      - "9000"
  database:
    image: mysql
    container_name: gothinkster_mysql
    ports:
      - "8013:3306"
    environment:
      - MYSQL_DATABASE=gothinkster
      - MYSQL_USER=gothinkster
      - MYSQL_PASSWORD=gothinkster
      - MYSQL_ALLOW_EMPTY_PASSWORD=true