version: '3'
services:
  nginx:
    build: ./docker/nginx
    volumes:
      - ./:/var/www/realworld/
    ports:
      - 80:80
    restart: always
    depends_on:
      - php-fpm
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./:/var/www/realworld/
    expose:
      - 9000
    ports:
      - 9000:9000
    links:
      - mysql:realworld.dev
  mysql:
    image: mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=realworld
      - MYSQL_USER=realworld
      - MYSQL_PASSWORD=realworld
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
