---
- hosts: localhost

  vars:
    packages:
      - php
      - composer
      - docker
      - docker-compose

  tasks:
    - pacman:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
      when: ansible_distribution == "Manjaro Linux" or ansible_distribution == "Arch Linux"

    - apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
      when: when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

    - service:
        name: docker
        state: started
