---
- hosts: all

  vars:
    packages:
      - php
      - composer
      - docker
      - docker-compose

  tasks:
    - pacman:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"

    - pacman:
        name: mysql-clients
        state: present
      when: ansible_distribution == "Manjaro Linux" or ansible_distribution == "Arch Linux"

    - service:
        name: docker
        state: started
