security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        login:
            pattern:  ^/api/users/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/users/login_check
                login_path:               /api/users/login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/users$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }