services:
    use_case.register_user:
        class: AppBundle\UseCase\RegisterUserUseCase
        arguments:
            - '@repository.user'
            - '@encoder.password'

    repository.user:
        class: AppBundle\Repository\UserRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - AppBundle\Entity\User

    encoder.password:
        class: Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder
        arguments:
            - 12

    provider.user_token_view:
        class: AppBundle\Provider\UserTokenViewProvider
        arguments:
            - '@lexik_jwt_authentication.encoder'
